In [132]:
import numpy as np

a= np.array([1,2,3,4,5,6,7,8,9,10])

In [133]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
b= np.array([11,12,13,14,15,16,17,18,19,20])
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [135]:
a+b

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [136]:
ar=np.array([1,2,3,4,5,6,7,8,9,10])
ar.shape

(10,)

In [137]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [138]:
ar1= np.array([[1,2,3,4,5],[6,7,8,9,10]])
ar1.shape

(2, 5)

In [139]:
ar1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [140]:
ans= ar.reshape(5,2) + ar1.reshape(5,2)

In [141]:
np.hstack(ans)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])