In [3]:
import numpy as np
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [5]:

np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
np.logspace(2,4,8)

array([  100.        ,   193.06977289,   372.75937203,   719.685673  ,
        1389.49549437,  2682.69579528,  5179.47467923, 10000.        ])

In [7]:
np.random.rand(2,2,2) # generate random number between 0-1 of size 2x2x2 (3d matrix)

array([[[0.79756572, 0.56226679],
        [0.56630152, 0.61220698]],

       [[0.81188281, 0.3645034 ],
        [0.15159232, 0.9387829 ]]])

In [9]:
d= np.random.randint(0,10,size=(5,5))
d

array([[6, 3, 8, 1, 3],
       [4, 1, 3, 9, 2],
       [8, 8, 2, 2, 5],
       [4, 5, 4, 5, 9],
       [9, 0, 7, 9, 8]])

In [10]:
d[:,:] #acessing all the element

array([[6, 3, 8, 1, 3],
       [4, 1, 3, 9, 2],
       [8, 8, 2, 2, 5],
       [4, 5, 4, 5, 9],
       [9, 0, 7, 9, 8]])

In [11]:
d[:,1:4] #printing from column 1 to 4 

array([[3, 8, 1],
       [1, 3, 9],
       [8, 2, 2],
       [5, 4, 5],
       [0, 7, 9]])