In [3]:
import numpy as np
a=np.random.randint(0,9,size=(3,3))
b=np.ones((3,3))

In [4]:
a


array([[7, 7, 2],
       [6, 6, 6],
       [7, 6, 1]])

In [5]:
np.concatenate([a,b],axis=0)  #axis 0= verti  and axis 1= hori

array([[7., 7., 2.],
       [6., 6., 6.],
       [7., 6., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.hstack([a,b]) # horizontal stack

array([[7., 7., 2., 1., 1., 1.],
       [6., 6., 6., 1., 1., 1.],
       [7., 6., 1., 1., 1., 1.]])

In [7]:
##Spliting of np Data Structure

d= np.vstack([a,b]) #vertical stack

In [11]:
d

array([[7., 7., 2.],
       [6., 6., 6.],
       [7., 6., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
d1,d2 = np.vsplit(d,[2])

In [10]:
d1

array([[7., 7., 2.],
       [6., 6., 6.]])

In [12]:
d2

array([[7., 6., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
#Shape Size ndim
d.ndim

2

In [15]:
d.size

18

In [16]:
d.shape

(6, 3)

In [17]:
#Reshaping
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
a.shape

(10,)

In [22]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
a.sum(axis=0)  # np.max(a)//a.max() function and many more functions 

55